### ISSUE TITLE
not show vertex group

### ISSUE THREAD

**Issue by murasesyuka** [kozmof/vertex_tricker#1]
this great.
I hurried to install, try it. but not running.

I do "Shift-F" at edit-mode of "Body" object 
and It happend error as follows

````python
Traceback (most recent call last):
  File "C:\Users\murase\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\vertex_tricker.py", line 170, in draw
    items = get_v_groups(self, context)
  File "C:\Users\murase\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\vertex_tricker.py", line 39, in get_v_groups
    vertices = bpy.data.meshes[ob_name].vertices
KeyError: 'bpy_prop_collection[key]: key "Body" not found'

location: C:\Home\freetools\blender-2.77a-windows64\2.77\scripts\modules\bpy\ops.py:189
````

What do you know about something the cause ?

env : windows 10 : blender 2.76b / 2.77a

**Comment by kozmof** [comment]
Hi, thanks for submitting an issue. It looks bpy.data.meshes couldn't get the data of Object "Body". I'll check this issue in 1 week.

**Comment by kozmof** [comment]
Hi, I solved a problem. https://github.com/kozmof/vertex_tricker/commit/d07c68da4fea1f9315ef5e7d4222cf44b76ed77e
